param([Parameter(Mandatory=$true)][string]$SourceDirectory)
$ErrorActionPreference='Stop'; $root=$PSScriptRoot; $bookRoot=Join-Path $root 'books'
$cats=@(
@{slug='literature';label='문학';source='literature';count=20},@{slug='humanities';label='인문/사회';source='social_sciences';count=15},
@{slug='business';label='경제/경영';source='business';count=15},@{slug='science';label='과학/기술';source='physics';count=15},
@{slug='art';label='예술';source='art';count=10},@{slug='children';label='어린이';source='juvenile_literature';count=15},
@{slug='language';label='어학';source='linguistics';count=10})
function E([object]$v){[System.Net.WebUtility]::HtmlEncode([string]$v)}
$all=[Collections.Generic.List[object]]::new();$used=@{};$rank=0
foreach($cat in $cats){$works=@((Get-Content -Raw -Encoding UTF8 -LiteralPath (Join-Path $SourceDirectory "openlibrary-$($cat.source).json")|ConvertFrom-Json).works);$n=0
 foreach($w in $works){if($n-ge$cat.count){break};if(!$w.key-or$used[[string]$w.key]){continue};$used[[string]$w.key]=$true;$rank++;$n++
  $all.Add([pscustomobject]@{id=('B{0:D3}'-f$rank);rank=$rank;category=$cat.slug;category_name=$cat.label;title=[string]$w.title;author=$(if($w.authors.Count){$w.authors[0].name}else{'Unknown author'});year=[int]$w.first_publish_year;cover_id=[string]$w.cover_id;work_key=[string]$w.key;price=9000+(($rank*1370)%21000);rating=4+(($rank*7)%10)/10;reviews=18+(($rank*37)%480)})}
 if($n-ne$cat.count){throw "$($cat.label): $n권만 확보"}}
function Card($b,$display){$cover=$(if($b.cover_id){"https://covers.openlibrary.org/b/id/$($b.cover_id)-L.jpg"}else{'https://placehold.co/240x360?text=No+Cover'});$list=[math]::Ceiling(($b.price/.9)/100)*100;$point=[math]::Floor($b.price*.05/10)*10
@"
<article class="book" data-id="$($b.id)" data-category="$($b.category)" data-category-name="$(E $b.category_name)" data-cover-id="$($b.cover_id)"><span class="rank">$display</span><a class="cover-link" href="https://openlibrary.org$($b.work_key)"><img class="cover" src="$(E $cover)" alt="$(E $b.title) 책 표지" loading="lazy"></a><div class="book-info"><div class="badges"><span class="badge category-badge">$(E $b.category_name)</span><span class="badge">무료배송</span></div><a class="title" href="https://openlibrary.org$($b.work_key)">$(E $b.title)</a><p class="subtitle">$(E $b.category_name) 분야에서 꾸준히 읽히는 추천 도서</p><div class="author-line"><span class="author">$(E $b.author)</span><span class="publisher">Open Library Edition</span><span class="published">$($b.year)년 초판</span></div><div class="review"><span class="rating" data-score="$($b.rating.ToString('N1'))">★ $($b.rating.ToString('N1'))</span> · 리뷰 $($b.reviews)</div></div><div class="price-box"><span class="discount">10%</span><span class="price">$($b.price.ToString('N0'))원</span><span class="list-price">$($list.ToString('N0'))원</span><span class="point">적립금 $($point.ToString('N0'))원</span><span class="delivery">내일 도착 예정</span></div><div class="actions"><button class="buy">바로구매</button><button class="cart">장바구니</button><button>♡ 찜하기</button></div></article>
"@}
function Side($prefix,$active){(($cats|ForEach-Object{$cl=$(if($_.slug-eq$active){' class="active"'}else{''});"<li$cl><a href=`"$prefix$($_.slug)/page1.html`">$($_.label) <span>$($_.count)</span></a></li>"})-join'')}
function Pager($cur,$total){$x=for($p=1;$p-le$total;$p++){if($p-eq$cur){"<span class=`"current`">$p</span>"}else{"<a href=`"page$p.html`">$p</a>"}};if($cur-lt$total){$x+="<a class=`"next`" rel=`"next`" href=`"page$($cur+1).html`">다음 ›</a>"};$x-join''}
function Page($title,$css,$baseRoot,$guide,$sidePrefix,$active,$items,$page,$pages,$total){$cards=for($i=0;$i-lt$items.Count;$i++){Card $items[$i](($page-1)*10+$i+1)}
@"
<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>$(E $title) | 북마켓</title><link rel="stylesheet" href="$css"></head><body><div class="utility"><div class="utility-inner"><a href="#">로그인</a><a href="#">회원가입</a><a href="#">주문배송</a><a href="$guide">고객센터</a></div></div><header class="main-header"><div class="header-inner"><a class="logo" href="$baseRoot/index.html">BOOK<b>MARKET</b></a><form class="search"><input type="search" placeholder="찾고 싶은 책을 검색해 보세요"><button>⌕</button></form><div class="header-icons"><a href="#"><span>♡</span>찜한 상품</a><a href="#"><span>🛒</span>장바구니</a></div></div></header><nav class="category-nav"><div class="nav-inner"><a class="all-menu" href="#">☰ 전체 카테고리</a><a href="$baseRoot/books/page1.html">베스트</a><a href="#">신상품</a><a href="#">국내도서</a><a href="#">외국도서</a><a href="#">eBook</a><a class="hot" href="#">특가</a></div></nav><main><div class="breadcrumb">홈 &gt; 도서 &gt; $(E $title)</div><div class="content-head"><h1>$(E $title)</h1><p>$page / $pages 페이지</p></div><div class="layout"><aside class="side"><h2>도서 카테고리</h2><ul>$(Side $sidePrefix $active)</ul></aside><section><div class="toolbar"><span>총 <strong>$total</strong>개의 상품</span><div class="sort"><a class="on" href="#">판매량순</a><a href="#">신상품순</a><a href="#">낮은가격순</a><a href="#">평점순</a></div></div><div class="book-list">$($cards-join'')</div><nav class="pagination">$(Pager $page $pages)</nav></section></div></main><footer class="store-footer"><div class="footer-inner"><strong>BOOKMARKET</strong>교육용 가상 서점이며 실제 결제는 이루어지지 않습니다. 서지와 표지는 Open Library 자료를 사용합니다.</div></footer></body></html>
"@}
$catalog=[Collections.Generic.List[object]]::new()
for($i=0;$i-lt20;$i++){foreach($cat in $cats){$item=@($all|Where-Object { $_.category -eq $cat.slug })[$i];if($null-ne$item){$catalog.Add($item)}}}
for($p=1;$p-le10;$p++){$slice=@($catalog|Select-Object -Skip(($p-1)*10)-First 10);Set-Content -Encoding UTF8 -LiteralPath(Join-Path $bookRoot "page$p.html")-Value(Page '전체 베스트셀러' '../assets/style.css' '..' '../guide.html' 'categories/' '' $slice $p 10 100)}
foreach($cat in $cats){$dir=Join-Path $bookRoot "categories/$($cat.slug)";New-Item -ItemType Directory -Force -Path $dir|Out-Null;$set=@($all|Where-Object { $_.category -eq $cat.slug });$pages=[math]::Ceiling($set.Count/10);for($p=1;$p-le$pages;$p++){$slice=@($set|Select-Object -Skip(($p-1)*10)-First 10);Set-Content -Encoding UTF8 -LiteralPath(Join-Path $dir "page$p.html")-Value(Page "$($cat.label) 도서" '../../../assets/style.css' '../../..' '../../../guide.html' '../' $cat.slug $slice $p $pages $set.Count)}}
$catalog|ConvertTo-Json -Depth 4|Set-Content -Encoding UTF8 -LiteralPath(Join-Path $root 'api/books.json');Write-Output "100권, 7개 카테고리 생성 완료"
